import { AuthProvider } from '@/lib/components/AuthProvider'
import type { Metadata } from 'next'
import { Header } from '@/lib/components/Header'
import { Footer } from '@/lib/components/Footer'
import { Toaster } from 'sonner'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next Auth Test',
  description: 'Generated by Next Auth Test',
}

interface RootLayoutType {
  children: React.ReactNode
}

export default async function RootLayout({ children }: Readonly<RootLayoutType>) {
  return (
    <html lang="ko">
      <body>
        <AuthProvider>
          <Toaster position="top-center" theme="light" richColors closeButton />
          <Header />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
