name: pnpm Nextjs standalone CI

on:
  push:
    branches: [main]

env:
  DOCKER_BUILDKIT: 1 # BuildKit 활성화
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/next-auth-test
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          file: Dockerfile
          secrets: |
            id=NEXT_PUBLIC_SUPABASE_URL,src=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            id=NEXT_PUBLIC_SUPABASE_ANON_KEY,src=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            id=RESET_PW_JWT,src=${{ secrets.RESET_PW_JWT }}
            id=DATABASE_URL,src=${{ secrets.DATABASE_URL }}
            id=DIRECT_URL,src=${{ secrets.DIRECT_URL }}
            id=NEXTAUTH_URL,src=${{ secrets.NEXTAUTH_URL }}
            id=NEXTAUTH_SECRET,src=${{ secrets.NEXTAUTH_SECRET }}
            id=NEXT_PUBLIC_PROJECT_DIR,src=${{ secrets.NEXT_PUBLIC_PROJECT_DIR }}
            id=NEXT_PUBLIC_BASE_URL,src=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            id=EMAIL_SERVER,src=${{ secrets.EMAIL_SERVER }}
            id=EMAIL_PORT,src=${{ secrets.EMAIL_PORT }}
            id=EMAIL_USER,src=${{ secrets.EMAIL_USER }}
            id=EMAIL_PASSWORD,src=${{ secrets.EMAIL_PASSWORD }}
            id=NEXT_PUBLIC_SUPABASE_STORAGE_URL,src=${{ secrets.NEXT_PUBLIC_SUPABASE_STORAGE_URL }}
