name: pnpm Nextjs standalone CI

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/next-auth-test
  VERSION: ${{ github.sha }}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          file: Dockerfile
          build-args: |
            NODE_ENV=production

  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:latest
          docker run -d \
            -e NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            -e NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            -e RESET_PW_JWT=${{ secrets.RESET_PW_JWT }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DIRECT_URL=${{ secrets.DIRECT_URL }} \
            -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -e NEXT_PUBLIC_PROJECT_DIR=${{ secrets.NEXT_PUBLIC_PROJECT_DIR }} \
            -e NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} \
            -e EMAIL_SERVER=${{ secrets.EMAIL_SERVER }} \
            -e EMAIL_PORT=${{ secrets.EMAIL_PORT }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
            -e NEXT_PUBLIC_SUPABASE_STORAGE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_STORAGE_URL }} \
            -p 3000:3000 ${{ env.DOCKER_IMAGE }}:latest
